<?php

/**
 * @file
 * Contains github_auth.module.
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function github_auth_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the github_auth module.
    case 'help.page.github_auth':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('GitHub Login Auth') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function github_auth_theme() {
  return [
    'github_auth' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function github_auth_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  $form['github_auth'] = [
    '#type' => 'container',
    '#suffix' => '<div class="github_auth__separator">' . t('Or create new account') . '</div>',
    '#weight' => -1,
    '#attributes' => [
      'class' => ['github_auth__link'],
    ],
    'github_link' => [
      '#type' => 'link',
      '#title' => t('Login with GitHub'),
      '#url' => Url::fromUri('https://github.com/login/oauth/authorize', [
        'absolute' => TRUE,
        'attributes' => [
          'title' => t('Login with GitHub'),
          'class' => ['github_auth__link'],
        ],
      ]),
    ]
  ];

  $form['#attached'] = [
    'library' => ['github_auth/github_auth']
  ];
}
